### ISSUE TITLE
[bug] side-bar menu item text is not visible on hover

### ISSUE THREAD

**Issue by qurban-18** [spa5k/quran#251]
## Bug description
The sidebar menu item text is not visible on hover due to the background color and text color being the same.

## Steps to Reproduce
Navigate to the sidebar menu.
Hover over a menu item.

## Expected Behavior
The text of the menu item should be visible and distinguishable from the background color when hovering over it.

## Screenshot
<img width="960" alt="chrome_41xOREciWq" src="https://github.com/spa5k/quran/assets/61090991/b2bf3ca6-2e93-41aa-b07a-c9a0f7cbc3c3">

**Comment by spa5k** [comment]
Thanks for the report, we will soon start working again on this project with more focus and fix it on latest.

@BasiOfficial @golam71 looks like it got messed up in that UI improvements branch. Check it.
