### ISSUE TITLE
[bug] settings has an error of undefined value

### ISSUE THREAD

**Issue by qurban-18** [spa5k/quran#252]
## Bug description
An undefined value error is shown when the user clicks on the Quran tab by going to the settings page.

## Steps to reproduce
1- Click on the settings icon
2- select the Quran tab

## Screenshot
<img width="454" alt="w7KLgipvqo" src="https://github.com/spa5k/quran/assets/61090991/d87074e2-4cea-4bc4-b50a-d87a64dd13d8">

**Comment by spa5k** [comment]
Thanks for the report, looked like something went wrong, will need to fix it.

**Comment by spa5k** [comment]
It has been fixed now.
